kind: Service
apiVersion: v1
metadata:
  name: mock-frontend-svc
spec:
  type: LoadBalancer
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  selector:
    app: mock-frontend