kind: Deployment
apiVersion: apps/v1
metadata:
  name: mock-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mock-frontend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: mock-frontend
    spec:
      containers:
      - name: mock-frontend-pod
        image: rbwecondevacr01.azurecr.io/mock-frontend:0.0.2
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: backendUri
          value: http://mock-backend-svc.default.svc.cluster.local/api/values