kind: Deployment
apiVersion: apps/v1
metadata:
  name: mock-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mock-backend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: mock-backend
    spec:
      containers:
      - name: mock-backend-pod
        image: rbwecondevacr01.azurecr.io/mock-backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80